# Generated by Django 5.1.3 on 2024-11-22 16:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
