# Generated by Django 5.1.3 on 2024-11-22 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.ForeignKey(help_text='If you dont see any category here, please contact admins.', on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='categories.category', verbose_name='Category'),
        ),
    ]
