# Generated by Django 5.1.3 on 2024-11-22 19:00

import django.core.validators
import django.db.models.deletion
import snapxPhotography.contests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options'),
        ('contests', '0002_alter_contest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='requirements',
            field=models.TextField(default='a', help_text='Please write down what requirements this contest should have', max_length=255, verbose_name='Requirements'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='award',
            field=models.PositiveIntegerField(help_text='Prize amount in currency (e.g., USD), maximum 5 digits', validators=[django.core.validators.MaxLengthValidator(5, message='Please enter a 5 digit number!!!')], verbose_name='Award'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='deadline',
            field=models.DateField(help_text='Deadline for contest submissions', validators=[snapxPhotography.contests.validators.DateValidator()], verbose_name='Deadline Date'),
        ),
    ]
