# Generated by Django 5.1.3 on 2024-11-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_contest_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['name']},
        ),
    ]
