# Generated by Django 5.1.3 on 2024-11-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myappuser',
            options={'verbose_name': 'Account'},
        ),
    ]
