# Generated by Django 5.1.3 on 2024-11-16 17:49

import cloudinary.models
import snapxPhotography.accounts.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_date_of_birth_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[snapxPhotography.accounts.validators.ProfileImageValidator(max_size=3)], verbose_name='Profile Picture'),
        ),
    ]
