# Generated by Django 5.1.3 on 2024-11-16 20:59

import django.core.validators
import snapxPhotography.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number must be in format: 088888888.', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), snapxPhotography.accounts.validators.PhoneNumberValidator()], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[snapxPhotography.accounts.validators.NameValidator(), django.core.validators.MinLengthValidator(2, 'Your First Name must be between 2 and 30 characters.')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[snapxPhotography.accounts.validators.NameValidator(), django.core.validators.MinLengthValidator(30, 'Your Last Name must be between 2 and 30 characters.')], verbose_name='Last Name'),
        ),
    ]
