# Generated by Django 5.1.3 on 2024-11-16 21:20

import django.core.validators
import snapxPhotography.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_address_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[snapxPhotography.accounts.validators.NameValidator(), django.core.validators.MinLengthValidator(2, 'Your Last Name must be between 2 and 30 characters.')], verbose_name='Last Name'),
        ),
    ]
