# Generated by Django 5.1.3 on 2024-11-22 10:41

import django.core.validators
import snapxPhotography.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_address_alter_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[snapxPhotography.accounts.validators.NameValidator(), django.core.validators.MinLengthValidator(2, 'Your First Name must be between 2 and 30 characters.')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[snapxPhotography.accounts.validators.NameValidator(), django.core.validators.MinLengthValidator(2, 'Your Last Name must be between 2 and 30 characters.')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number must be in format: 088888888.', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Your Phone Number must be exactly 10 digits in given format!'), snapxPhotography.accounts.validators.PhoneNumberValidator()], verbose_name='Phone Number'),
        ),
    ]
