# Generated by Django 5.1.3 on 2024-11-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='vote',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
