# Generated by Django 5.1.3 on 2024-12-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_options_photo_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-vote', 'uploaded_at']},
        ),
    ]
